<?php

namespace XIVDB\Apps\GameData;

trait GamePatches
{
	//
	// Get patch list
	//
	public function getPatchList()
	{
		$dbs = $this->getModule('database');

		$dbs->QueryBuilder
			->select('*')
			->from('db_patch')
			->order('patch', 'desc');

		return $dbs->get()->all();
	}

	//
	// Get a single patch
	//
	public function getPatch($id)
	{
		$dbs = $this->getModule('database');

		$dbs->QueryBuilder
			->select('*')
			->from('db_patch')
			->where('patch = :id')
			->bind(':id', $id);

		return $dbs->get()->one();
	}

	//
	// Get latest patch
	//
	public function getLatestPatch()
	{
		$dbs = $this->getModule('database');

		$dbs->QueryBuilder
			->select('*')
			->from('db_patch')
			->order('patch', 'desc');

		return $dbs->get()->one();
	}

	//
	// Create a patch folder
	//
	public function createPatchFolder($editing)
	{
		// check if folder exists (and on dev)
		$folder = ROOT_EXTRACTS .'/'. $editing['folder'];
		if (DEV && $editing['folder'] && !is_dir($folder)) {
			mkdir($folder);
			mkdir($folder .'/explorer');
			mkdir($folder .'/libra');
			mkdir($folder .'/python');
			mkdir($folder .'/saint');

			// write new defines
			$directories = glob(ROOT_EXTRACTS . '/*' , GLOB_ONLYDIR);
			$defines = [];

			// prepare defines
			foreach($directories as $dir)
			{
				// only handle those with extract in the name
				if (stripos($dir, 'extract-') !== false)
				{
					$folder = str_ireplace(ROOT_EXTRACTS, null, $dir);
					$key = 'EXTRACT_'. str_ireplace('/extract-', null, $folder);

					$defines[$key] = $folder;
				}
			}

			// get current and previous patch folders
			$current = array_slice($defines, -1, 1);
			$previous = array_slice($defines, -2, 1);
			$current = reset($current);
			$previous = reset($previous);

			// begin file string
			$string = [];
			$string[] = '<?php ';
			$string[] = '// This file is auto generated by the dashboard patch CMS';

			// add defines to string
			foreach($defines as $key => $value)
			{
				$string[] = sprintf("define('%s', '%s');", $key, $value);
			}

			$string[] = sprintf("define('CURRENT_PATCH', '%s');", $current);
			$string[] = sprintf("define('PREVIOUS_PATCH', '%s');", $previous);
			$string = implode("\n", $string);

			// save defines
			file_put_contents(ROOT_APP .'/settings.patches.php', $string);
		}
	}
}
